import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster, toast } from 'sonner'
import Navbar from "@/components/navbar";
import RecoilContextProvider, { ReactQuearyProvider } from "@/lib/recoilContextProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "V-choose",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="flex flex-col  min-h-screen  bg-white dark:bg-gray-900 ">
          <Navbar></Navbar>
          <SessionProvider>
          <Toaster richColors />
          <RecoilContextProvider>
          <SessionProvider> 
            <ReactQuearyProvider>
              <div className='pt-20'>
        {children}
        </div>
        <ReactQueryDevtools />
        </ReactQuearyProvider>
        </SessionProvider>
        </RecoilContextProvider>
        </SessionProvider>
        </div></body>
    </html>
  );
}
